
version: '3.4'

services:
  dadi:
    image: dadi
    build:
      context: .
      dockerfile: dadi/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
