
version: '3.4'

services:
  primalezione:
    image: primalezione
    build:
      context: .
      dockerfile: Prima lezione/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
